### ISSUE TITLE
[Bug] When the staging engine crashes, the worker process doesn't deallocate CUDA memory properly sometimes 

### ISSUE THREAD

**Issue by masahi** [octoml/mlc-llm#143]
I've seen it many times when I was developing something new and crashed the engine due to a bug. But I cannot find a way to reliably reproduce this. Also reported by @jroesch as this necessitates a manual server / container restart.

**Comment by sunggg** [comment]
Is this related to the zombie processes occupying the gpus after the server crashes?

**Comment by masahi** [comment]
yes, it is exactly that problem.
